TOPIC_NAME_SELECTOR = '#topic > h1 ::attr(data-title)'
TOPIC_ID_SELECTOR = '#topic > h1 ::attr(data-id)'
SET_SELECTOR = '#entry-item-list > li'
CURRENT_PAGE_SELECTOR = '.pager ::attr(data-currentpage)'
LAST_PAGE_SELECTOR = '.pager ::attr(data-pagecount)'
ENTRY_SELECTOR = ".content ::text"
LINK_SELECTOR = ".content > a"
ENTRY_ID_SELECTOR = "::attr(data-id)"
WRITER_SELECTOR = "::attr(data-author)"
ENTRY_DATE_SELECTOR = 'footer > div.info > div.entry-footer-bottom > div.footer-info > div > a.entry-date.permalink ::text'
FAV_NUM_SELECTOR = '::attr(data-favorite-count)'
AMATEUR_WRITER_SELECTOR = ".hidden"
